[package]
name = "ghostty_animation"
version = "0.1.0"
edition = "2021"

[dependencies]
alternate_screen_wrapper = { version = "0.1.1", features = ["crossterm"] }
crossterm = "0.28.1"
ratatui = "0.29.0"

[profile.release]
lto = true
codegen-units = 1
